const MOVIELISTDATA = {
  LOAD: "MOVIELISTDATA_LOAD",
  LOAD_SUCCESS: "MOVIELISTDATA_LOAD_SUCCESS",
  LOAD_FAIL: "MOVIELISTDATA_LOAD_FAIL",
};

const NAVBARTOGGLED = "NAVBARTOGGLED";
const NAVBARCLICKED = "NAVBARCLICKED";
const SEARCH = {
  LOAD: "SEARCH_LOAD",
  LOAD_SUCCESS: "SEARCH_LOAD_SUCCESS",
  LOAD_FAIL: "SEARCH_LOAD_FAIL",
};

const SINGLEMOVIE = {
  LOAD: "SINGLEMOVIE_LOAD",
  LOAD_SUCCESS: "SINGLEMOVIE_LOAD_SUCCESS",
  LOAD_FAIL: "SINGLEMOVIE_LOAD_FAIL",
};

const SIGNIN = "SIGNIN";
// const REGISTER = "REGISTER"
const SIGNOUT = "SIGNOUT";

export {
  MOVIELISTDATA,
  NAVBARTOGGLED,
  NAVBARCLICKED,
  SEARCH,
  SINGLEMOVIE,
  SIGNIN,
  // REGISTER,
  SIGNOUT,
};
