const MOVIELISTDATA = {
  LOAD: "MOVIELISTDATA_LOAD",
  LOAD_SUCCESS: "MOVIELISTDATA_LOAD_SUCCESS",
  LOAD_FAIL: "MOVIELISTDATA_LOAD_FAIL",
};

const NAVBARTOGGLED = "NAVBARTOGGLED";
const NAVBARCLICKED = "NAVBARCLICKED";
const SEARCH = {
  LOAD: "SEARCH_LOAD",
  LOAD_SUCCESS: "SEARCH_LOAD_SUCCESS",
  LOAD_FAIL: "SEARCH_LOAD_FAIL",
};

const SINGLEMOVIE = {
  LOAD: "SINGLEMOVIE_LOAD",
  LOAD_SUCCESS: "SINGLEMOVIE_LOAD_SUCCESS",
  LOAD_FAIL: "SINGLEMOVIE_LOAD_FAIL",
};

// const SIGNIN = {
//   LOAD: "SIGNIN_LOAD",
//   LOAD_SUCCESS: "SIGNIN_LOAD_SUCCESS",
//   LOAD_FAIL: "SIGNIN_LOAD_FAIL",
// };
// const REGISTER = {
//   LOAD: "REGISTER_LOAD",
//   LOAD_SUCCESS: "REGISTER_LOAD_SUCCESS",
//   LOAD_FAIL: "REGISTER_LOAD_FAIL",
// };
// const SIGNOUT = {
//   LOAD: "SIGNOUT_LOAD",
//   LOAD_SUCCESS: "SIGNOUT_LOAD_SUCCESS",
//   LOAD_FAIL: "SIGNOUT_LOAD_FAIL",
// };

export {
  MOVIELISTDATA,
  NAVBARTOGGLED,
  NAVBARCLICKED,
  SEARCH,
  SINGLEMOVIE,
  // SIGNIN,
  // REGISTER,
  // SIGNOUT,
};
