const MOVIELISTDATA = {
  LOAD: "MOVIELISTDATA_LOAD",
  LOAD_SUCCESS: "MOVIELISTDATA_LOAD_SUCCESS",
  LOAD_FAIL: "MOVIELISTDATA_LOAD_FAIL",
};

const NAVBARTOGGLED = "NAVBARTOGGLED";
const NAVBARCLICKED = "NAVBARCLICKED";

export { MOVIELISTDATA, NAVBARTOGGLED, NAVBARCLICKED };
